### ISSUE TITLE
Error on Ember 3.0.0

### ISSUE THREAD

**Issue by mmun** [rwjblue/ember-named-arguments-polyfill#1]
Ember 3.0.0 contains an assertion that prevents this addon from working unless the `ember-glimmer-named-arguments` feature is enabled. Here's the line that asserts:

https://github.com/emberjs/ember.js/blob/master/packages/ember-template-compiler/lib/plugins/assert-reserved-named-arguments.ts#L31

**Comment by rwjblue** [comment]
Hmm, I don't think this is correct. We explicitly run our tests against Ember 3.0 and they are passing ([see recent job here](https://travis-ci.org/rwjblue/ember-named-arguments-polyfill/jobs/388972744)).

**Comment by rwjblue** [comment]
This may be a similar issue to https://github.com/rwjblue/ember-angle-bracket-invocation-polyfill/issues/18 (assuming that you hit this when using the inline compiler vs ember-cli-htmlbars).  Can you confirm which versions of `ember-cli-htmlbars-inline-precompile`, `ember-source`, `ember-named-arguments-polyfill` you are using?
